version: '3.8'

services:
  nginx:
    image: nginx:alpine
    container_name: caixadigital_nginx
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/ssl:/etc/nginx/ssl:ro
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - backend
    networks:
      - caixadigital_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: caixadigital_backend
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000 --workers 4 --threads 2 --worker-class gthread --timeout 60 --access-logfile - --error-logfile -
    volumes:
      - static_volume:/app/staticfiles
      - media_volume:/app/media
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_ENV=production
    depends_on:
      - db
      - redis
    networks:
      - caixadigital_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  celery_worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: caixadigital_celery_worker
    command: celery -A core worker -l info --concurrency=2
    volumes:
      - media_volume:/app/media
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_ENV=production
    depends_on:
      - db
      - redis
    networks:
      - caixadigital_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  celery_beat:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: caixadigital_celery_beat
    command: celery -A core beat -l info --scheduler django_celery_beat.schedulers:DatabaseScheduler
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_ENV=production
    depends_on:
      - db
      - redis
    networks:
      - caixadigital_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  channels:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: caixadigital_channels
    command: daphne -b 0.0.0.0 -p 8001 core.asgi:application
    env_file:
      - ./backend/.env
    environment:
      - DJANGO_ENV=production
    depends_on:
      - db
      - redis
    networks:
      - caixadigital_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  db:
    image: postgres:15-alpine
    container_name: caixadigital_db
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./scripts/postgres-backup.sh:/usr/local/bin/backup.sh:ro
    env_file:
      - ./backend/.env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    networks:
      - caixadigital_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "50m"
        max-file: "5"

  redis:
    image: redis:7-alpine
    container_name: caixadigital_redis
    command: redis-server --requirepass ${REDIS_PASSWORD} --maxmemory 512mb --maxmemory-policy allkeys-lru
    volumes:
      - redis_data:/data
    networks:
      - caixadigital_network
    restart: unless-stopped
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

volumes:
  postgres_data:
  redis_data:
  static_volume:
  media_volume:

networks:
  caixadigital_network:
    driver: bridge