# Generated by Django 4.2.16 on 2025-05-29 18:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('companies', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('notification_type', models.CharField(choices=[('low_balance', 'Saldo Baixo'), ('large_transaction', 'Transação Grande'), ('recurring_payment', 'Pagamento Recorrente'), ('sync_error', 'Erro de Sincronização'), ('report_ready', 'Relatório Pronto'), ('subscription_expiring', 'Assinatura Expirando'), ('user_invited', 'Usuário Convidado'), ('budget_exceeded', 'Orçamento Excedido'), ('ai_insight', 'Insight IA'), ('custom', 'Personalizado')], max_length=30, verbose_name='notification type')),
                ('title', models.CharField(max_length=200, verbose_name='title')),
                ('message', models.TextField(verbose_name='message')),
                ('data', models.JSONField(default=dict, verbose_name='additional data')),
                ('action_url', models.CharField(blank=True, max_length=500, verbose_name='action URL')),
                ('priority', models.CharField(choices=[('low', 'Baixa'), ('medium', 'Média'), ('high', 'Alta'), ('urgent', 'Urgente')], default='medium', max_length=10, verbose_name='priority')),
                ('is_read', models.BooleanField(default=False, verbose_name='is read')),
                ('read_at', models.DateTimeField(blank=True, null=True, verbose_name='read at')),
                ('email_sent', models.BooleanField(default=False, verbose_name='email sent')),
                ('email_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='email sent at')),
                ('push_sent', models.BooleanField(default=False, verbose_name='push sent')),
                ('push_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='push sent at')),
                ('sms_sent', models.BooleanField(default=False, verbose_name='SMS sent')),
                ('sms_sent_at', models.DateTimeField(blank=True, null=True, verbose_name='SMS sent at')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='expires at')),
                ('company', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='companies.company')),
            ],
            options={
                'verbose_name': 'Notification',
                'verbose_name_plural': 'Notifications',
                'db_table': 'notifications',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='NotificationTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='template name')),
                ('notification_type', models.CharField(choices=[('low_balance', 'Saldo Baixo'), ('large_transaction', 'Transação Grande'), ('recurring_payment', 'Pagamento Recorrente'), ('sync_error', 'Erro de Sincronização'), ('report_ready', 'Relatório Pronto'), ('subscription_expiring', 'Assinatura Expirando'), ('user_invited', 'Usuário Convidado'), ('budget_exceeded', 'Orçamento Excedido'), ('ai_insight', 'Insight IA'), ('custom', 'Personalizado')], max_length=30, verbose_name='notification type')),
                ('title_template', models.CharField(max_length=200, verbose_name='title template')),
                ('message_template', models.TextField(verbose_name='message template')),
                ('send_email', models.BooleanField(default=True, verbose_name='send email')),
                ('send_push', models.BooleanField(default=True, verbose_name='send push notification')),
                ('send_sms', models.BooleanField(default=False, verbose_name='send SMS')),
                ('is_active', models.BooleanField(default=True, verbose_name='is active')),
                ('is_system', models.BooleanField(default=True, verbose_name='is system template')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='created at')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
            ],
            options={
                'verbose_name': 'Notification Template',
                'verbose_name_plural': 'Notification Templates',
                'db_table': 'notification_templates',
            },
        ),
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_enabled', models.BooleanField(default=True, verbose_name='email notifications')),
                ('push_enabled', models.BooleanField(default=True, verbose_name='push notifications')),
                ('sms_enabled', models.BooleanField(default=False, verbose_name='SMS notifications')),
                ('type_preferences', models.JSONField(default=dict, verbose_name='type preferences')),
                ('quiet_hours_start', models.TimeField(blank=True, null=True, verbose_name='quiet hours start')),
                ('quiet_hours_end', models.TimeField(blank=True, null=True, verbose_name='quiet hours end')),
                ('send_daily_digest', models.BooleanField(default=False, verbose_name='send daily digest')),
                ('send_weekly_digest', models.BooleanField(default=True, verbose_name='send weekly digest')),
                ('digest_time', models.TimeField(default='09:00', verbose_name='digest time')),
                ('low_balance_threshold', models.DecimalField(decimal_places=2, default=1000.0, max_digits=15, verbose_name='low balance threshold')),
                ('large_transaction_threshold', models.DecimalField(decimal_places=2, default=5000.0, max_digits=15, verbose_name='large transaction threshold')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='updated at')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='notification_preferences', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Notification Preference',
                'verbose_name_plural': 'Notification Preferences',
                'db_table': 'notification_preferences',
            },
        ),
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('email', 'Email'), ('push', 'Push'), ('sms', 'SMS'), ('in_app', 'In-App')], max_length=20, verbose_name='channel')),
                ('success', models.BooleanField(default=False, verbose_name='success')),
                ('error_message', models.TextField(blank=True, verbose_name='error message')),
                ('recipient', models.CharField(max_length=200, verbose_name='recipient')),
                ('provider', models.CharField(blank=True, max_length=50, verbose_name='provider')),
                ('provider_message_id', models.CharField(blank=True, max_length=200, verbose_name='provider message ID')),
                ('attempted_at', models.DateTimeField(auto_now_add=True, verbose_name='attempted at')),
                ('notification', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='notifications.notification')),
            ],
            options={
                'verbose_name': 'Notification Log',
                'verbose_name_plural': 'Notification Logs',
                'db_table': 'notification_logs',
                'ordering': ['-attempted_at'],
            },
        ),
        migrations.AddField(
            model_name='notification',
            name='template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notifications.notificationtemplate'),
        ),
        migrations.AddField(
            model_name='notification',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['user', 'is_read'], name='notificatio_user_id_a4dd5c_idx'),
        ),
        migrations.AddIndex(
            model_name='notification',
            index=models.Index(fields=['created_at'], name='notificatio_created_e4c995_idx'),
        ),
    ]
